// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/search-tenders.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Connect this MCP server with OAuth first." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/search-tenders.ts
var search_tenders_default = defineTool({
  name: "search_tenders",
  title: "Search tenders",
  description: "Search UK public sector tender notices by keyword, buyer, source and publication window. Returns the most recently published matches.",
  inputSchema: {
    keyword: z.string().optional().describe("Free text matched against tender title and description."),
    buyer: z.string().optional().describe("Buyer / contracting authority name (partial match)."),
    source: z.string().optional().describe("Source code, e.g. cf, fts, contracts_scotland, ccs_digital_outcomes."),
    published_from: z.string().optional().describe("ISO date. Only tenders published on or after this date."),
    open_only: z.boolean().optional().describe("Only tenders whose submission deadline is still in the future."),
    limit: z.number().optional().describe("Maximum results to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ keyword, buyer, source, published_from, open_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("tenders").select(
      "id, external_id, title, description, buyer_name, source, source_url, published_at, deadline_at, value_min, value_max, currency, region, primary_cpv"
    ).order("published_at", { ascending: false, nullsFirst: false }).limit(take);
    if (keyword) query = query.or(`title.ilike.%${keyword}%,description.ilike.%${keyword}%`);
    if (buyer) query = query.ilike("buyer_name", `%${buyer}%`);
    if (source) query = query.eq("source", source);
    if (published_from) query = query.gte("published_at", published_from);
    if (open_only) query = query.gte("deadline_at", (/* @__PURE__ */ new Date()).toISOString());
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, tenders: data ?? [] });
  }
});

// src/lib/mcp/tools/get-tender.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_tender_default = defineTool2({
  name: "get_tender",
  title: "Get tender",
  description: "Fetch the full detail of a single tender notice by its id or external id.",
  inputSchema: {
    id: z2.string().optional().describe("Internal tender UUID."),
    external_id: z2.string().optional().describe("Source external id / OCID of the tender.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, external_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    if (!id && !external_id) return errorResult("Provide either id or external_id.");
    let query = supabaseForUser(ctx).from("tenders").select(
      "id, external_id, ocid, title, description, buyer_name, buyer_type, source, source_url, status, derived_status, notice_type, procedure_type, published_at, deadline_at, contract_start, contract_end, award_date, value_min, value_max, currency, region, country, sector, primary_cpv, cpv_codes"
    ).limit(1);
    query = id ? query.eq("id", id) : query.eq("external_id", external_id);
    const { data, error } = await query.maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Tender not found.");
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-saved-bids.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_saved_bids_default = defineTool3({
  name: "list_saved_bids",
  title: "List saved bids",
  description: "List the bids in the signed-in user's organisation pipeline, optionally filtered by pipeline status.",
  inputSchema: {
    status: z3.string().optional().describe("Pipeline status filter, e.g. interested, bidding, submitted, won, lost."),
    limit: z3.number().optional().describe("Maximum results to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabaseForUser(ctx).from("saved_bids").select(
      "id, title, buyer, source, source_url, status, value, deadline_date, published_date, notes, created_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, bids: data ?? [] });
  }
});

// src/lib/mcp/tools/list-saved-searches.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_saved_searches_default = defineTool4({
  name: "list_saved_searches",
  title: "List saved searches",
  description: "List the saved searches (daily digest alerts) belonging to the signed-in user's organisation, including their filters and last alert time.",
  inputSchema: {
    active_only: z4.boolean().optional().describe("Only return saved searches that are currently active.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("saved_searches").select(
      "id, name, active, source, buyer, supplier, cpv, notice_type, min_value, max_value, published_from, published_to, filters, email_recipients, last_alerted_at, created_at"
    ).order("created_at", { ascending: false }).limit(100);
    if (active_only) query = query.eq("active", true);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, saved_searches: data ?? [] });
  }
});

// src/lib/mcp/tools/search-awards.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^4.4.3";
var search_awards_default = defineTool5({
  name: "search_awards",
  title: "Search contract awards",
  description: "Search awarded contracts by supplier and/or buyer name. Names are matched against the normalised canonical name so variants resolve to one entity.",
  inputSchema: {
    supplier: z5.string().optional().describe("Supplier / winning organisation name (partial match)."),
    buyer: z5.string().optional().describe("Buyer / contracting authority name (partial match)."),
    awarded_from: z5.string().optional().describe("ISO date. Only awards made on or after this date."),
    limit: z5.number().optional().describe("Maximum results to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ supplier, buyer, awarded_from, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    const canonical = (v) => v.trim().toLowerCase().replace(/&/g, "and");
    let query = supabaseForUser(ctx).from("awards").select(
      "id, supplier_name, buyer_name, award_value, currency, awarded_at, contract_start, contract_end, source, external_id, cpv_code"
    ).order("awarded_at", { ascending: false, nullsFirst: false }).limit(take);
    if (supplier) query = query.ilike("supplier_name_canonical", `%${canonical(supplier)}%`);
    if (buyer) query = query.ilike("buyer_name_canonical", `%${canonical(buyer)}%`);
    if (awarded_from) query = query.gte("awarded_at", awarded_from);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, awards: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "wklmkjmdrajxvvizkxkk";
var mcp_default = defineMcp({
  name: "bidintel-mcp",
  title: "BidIntel",
  version: "0.1.0",
  instructions: "Tools for BidIntel, a UK public sector tender and contract intelligence platform. Use `search_tenders` to find notices, `get_tender` for full detail of one notice, `search_awards` for awarded contracts by supplier or buyer, and `list_saved_bids` / `list_saved_searches` to read the signed-in user's own pipeline and alert configuration. All data is scoped to the authenticated user's organisation.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_tenders_default, get_tender_default, search_awards_default, list_saved_bids_default, list_saved_searches_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
