CREATE OR REPLACE VIEW public.tenders_cf_native AS
SELECT
  notice_id,
  payload->>'noticeIdentifier' as notice_identifier,
  payload->>'parentId' as parent_id,
  payload->>'title' as title,
  payload->>'description' as description,
  payload->>'noticeType' as notice_type,
  payload->>'noticeStatus' as status,
  payload->>'organisationName' as organisation_name,
  safe_ts(payload->>'publishedDate') as published_date,
  safe_ts(payload->>'deadlineDate') as closing_date,
  safe_ts(payload->>'awardedDate') as awarded_date,
  NULLIF(payload->>'awardedValue','')::numeric as awarded_value,
  payload->>'awardedSupplier' as awarded_supplier,
  payload->>'awardedToSme' as awarded_to_sme,
  payload->>'awardedToVcse' as awarded_to_vco,
  safe_ts(payload->>'approachMarketDate') as approach_market_date,
  NULLIF(payload->>'valueLow','')::numeric as value_low,
  NULLIF(payload->>'valueHigh','')::numeric as value_high,
  payload->>'postcode' as postcode,
  payload->>'coordinates' as coordinates,
  payload->>'region' as region,
  payload->>'regionText' as region_text,
  payload->>'nationwide' as nationwide,
  payload->>'sector' as sector,
  payload->>'cpvCodes' as cpv_codes,
  payload->>'cpvCodesExtended' as cpv_codes_extended,
  payload->>'cpvDescription' as cpv_description,
  payload->>'isSubNotice' as is_sub_contract,
  payload->>'isSuitableForSme' as suitable_for_sme,
  payload->>'isSuitableForVco' as suitable_for_vco,
  safe_ts(payload->>'start') as contract_start,
  safe_ts(payload->>'end') as contract_end,
  payload->>'lastNotifiableUpdate' as last_notifiable_update,
  payload as raw_json,
  fetched_at as created_at
FROM public.raw_cf_native;

CREATE OR REPLACE VIEW public.tenders_cf_bulk AS
SELECT
  notice_identifier as notice_id,
  ocid,
  notice_identifier,
  payload->>'title' as title,
  payload->>'description' as description,
  payload->>'noticeType' as notice_type,
  payload->>'noticeStatus' as status,
  payload->>'organisationName' as organisation_name,
  safe_ts(payload->>'publishedDate') as payload_published_date,
  safe_ts(payload->>'deadlineDate') as closing_date,
  safe_ts(payload->>'awardedDate') as awarded_date,
  NULLIF(payload->>'awardedValue','')::numeric as awarded_value,
  payload->>'awardedSupplier' as awarded_supplier,
  payload->>'awardedToSme' as awarded_to_sme,
  payload->>'awardedToVcse' as awarded_to_vco,
  NULLIF(payload->>'valueLow','')::numeric as value_low,
  NULLIF(payload->>'valueHigh','')::numeric as value_high,
  payload->>'postcode' as postcode,
  payload->>'region' as region,
  payload->>'regionText' as region_text,
  payload->>'nationwide' as nationwide,
  payload->>'sector' as sector,
  payload->>'cpvCodes' as cpv_codes,
  payload->>'cpvDescription' as cpv_description,
  payload->>'isSubNotice' as is_sub_contract,
  payload->>'isSuitableForSme' as suitable_for_sme,
  payload->>'isSuitableForVco' as suitable_for_vco,
  safe_ts(payload->>'start') as contract_start,
  safe_ts(payload->>'end') as contract_end,
  payload as raw_json,
  cf_bulk_upload.published_date as created_at
FROM public.cf_bulk_upload;

GRANT SELECT ON public.tenders_cf_native, public.tenders_cf_bulk TO authenticated;
