// ============================================================================
// The `supabase` client — now backed by AWS
// ============================================================================
//
// This file was generated by Lovable and said "Do not edit it directly". It is
// edited directly, because it is the seam: replacing what is behind this one
// export is what lets every OTHER file in src/ stay byte-identical.
//
// The exported object keeps the same three surfaces the app uses:
//
//   .from(...)            -> PostgREST on Fargate, via the real supabase-js
//                            query builder. postgrest-js IS what Supabase runs,
//                            so every existing .select().eq().order() call
//                            works unchanged against our own instance.
//
//   .auth.*               -> Cognito. See integrations/aws/cognito.ts.
//                            Same method names and return shapes as the four
//                            methods the app actually called.
//
//   .functions.invoke()   -> API Gateway. See integrations/aws/functions.ts.
//
// Import sites do not change:  import { supabase } from "@/integrations/supabase/client";

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { makePostgrestFetch } from "@/integrations/aws/postgrest";
import { invoke } from "@/integrations/aws/functions";
import * as cognito from "@/integrations/aws/cognito";

const POSTGREST_URL = import.meta.env.VITE_POSTGREST_URL;

if (!POSTGREST_URL) {
  console.error("[db] VITE_POSTGREST_URL is not set. Copy .env.example to .env.local.");
}

// The second argument is supabase-js's anon key. Standalone PostgREST has no
// such concept and the custom fetch strips the header, but createClient refuses
// an empty string — hence a placeholder rather than "".
const rest = createClient<Database>(POSTGREST_URL ?? "http://localhost", "postgrest-no-anon-key", {
  auth: {
    // All four disabled. supabase-js would otherwise construct a GoTrue client
    // that polls `${url}/auth/v1/...`, which on our URL is a PostgREST 404 on a
    // timer. Auth is Cognito's job; this client only builds queries.
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  },
  global: {
    // Rewrites the /rest/v1 prefix and attaches a fresh Cognito ID token per
    // request. See integrations/aws/postgrest.ts.
    fetch: makePostgrestFetch(),
  },
});

/**
 * The shape the app imports.
 *
 * `Pick<typeof rest, ...>` is load-bearing, not decoration. `rest.from.bind(rest)`
 * on its own collapses the method's generic signature, and every
 * `.from("profiles").select("id, email")` downstream degrades to `unknown` —
 * which surfaces as errors like "Property 'email' does not exist on type
 * 'unknown'" in files this migration is not supposed to touch. Declaring the
 * type restores the original signatures, so the Database generics keep flowing
 * and column-level typing is preserved.
 */
type SupabaseCompat = Pick<typeof rest, "from" | "rpc" | "schema"> & {
  auth: {
    getSession: typeof cognito.getSession;
    signInWithPassword: (creds: { email: string; password: string }) => Promise<cognito.SignInResult>;
    signOut: typeof cognito.signOut;
    onAuthStateChange: typeof cognito.onAuthStateChange;
  };
  functions: { invoke: typeof invoke };
};

export const supabase: SupabaseCompat = {
  // Bound so `this` is correct inside the client.
  from: rest.from.bind(rest),
  rpc: rest.rpc.bind(rest),
  schema: rest.schema.bind(rest),

  auth: {
    getSession: cognito.getSession,
    signInWithPassword: ({ email, password }: { email: string; password: string }) =>
      cognito.signInWithPassword(email, password),
    signOut: cognito.signOut,
    onAuthStateChange: cognito.onAuthStateChange,
  },

  functions: { invoke },
};
